/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SectionSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Subsection = IDL.Record({
  'body' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const Section = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subsections' : IDL.Vec(Subsection),
  'description' : IDL.Text,
});
export const SearchResult = IDL.Record({ 'id' : IDL.Nat, 'title' : IDL.Text });

export const idlService = IDL.Service({
  'getAllSections' : IDL.Func([], [IDL.Vec(SectionSummary)], ['query']),
  'getCalendarNotes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSection' : IDL.Func([IDL.Nat], [Section], ['query']),
  'saveCalendarNotes' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'searchSections' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SectionSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Subsection = IDL.Record({ 'body' : IDL.Text, 'subtitle' : IDL.Text });
  const Section = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subsections' : IDL.Vec(Subsection),
    'description' : IDL.Text,
  });
  const SearchResult = IDL.Record({ 'id' : IDL.Nat, 'title' : IDL.Text });
  
  return IDL.Service({
    'getAllSections' : IDL.Func([], [IDL.Vec(SectionSummary)], ['query']),
    'getCalendarNotes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSection' : IDL.Func([IDL.Nat], [Section], ['query']),
    'saveCalendarNotes' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'searchSections' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };